### ISSUE TITLE
git tracks the output of swig

### ISSUE THREAD

**Issue by boopcamt** [crowlogic/arb4j#121]
One time I was messing around and upon running bin/gaw somehow triggered Swig to update the version of the arb wrapper, which modified many files in src/arb/ that were being tracked by Git.

Given: any files that are generated from other tracked files (and that the developer would not modify) should not be tracked by Git and should be matched in the project .gitignore file.

Suggestion: add the files generated by Swig to .gitignore, or give them their own directory under src/arb/ and ignore that directory.

**Comment by crowlogic** [comment]
Good idea

**Comment by crowlogic** [comment]
Glad your getting into things.. all good suggestions . How do i check them
out ? If you think its all goodnl just merge them into master dont wait on
me for anything if its not right will figure it out then... its just not
the highest priority right now.. did you run the complex function animator
yet? I think you will think it's pretty cool considering the types of
things that can be generated whence the leak is fixed because it's like..
the undiscovered topology of a new world.. never seen before .. planning to
transition to javafx and opengl based gui so instead of magnitude and
angle(phase) of complex values being represented in a planar region only
there will also be the 3d representation where the real part represents the
height In the z axis for instance.or the imaginary part.  Or the absolute
value , etc

  I'll send ya more dollars tomorrowish

**Comment by crowlogic** [comment]
The idea was to make it build able from source without folks having to have
swig installed (users don't exist, only drug dealers and pimps have users
😉);

https://www.amazon.com/User-Illusion-Cutting-Consciousness-Penguin/dp/0140230122

**Comment by boopcamt** [comment]
Cool, will merge my changes after I'm more sure about the java side. Not planning to do any more housekeeping stuff unless it's a blocker; at this point i gotta use the library so I know more what's going on, anyway. So far it was just a few easy wins in your bin/ scripts, stuff that I already know a little about... but now it's Java Time!

I pushed a new branch for each pull request so a reviewer can merge them (I will do this later after I'm sure about java stuff). If you're synced, then you can git branch -l​ to list the branches, and git checkout issue-117​ to see the first one I did.
https://github.com/crowlogic/arb4j/pullshttps://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests

So today I entered java land. All this is new to me but I got maven set up and ran maven install​, which outputs this stuff into target/ :

arb4j-0.83.jar classes/ javadoc-bundle-options/ maven-status/
arb4j-0.83-sources.jar generated-sources/ maven-archiver/ site/

So I think I'm almost there. I want to give this a good try without eclipse so I can better understand what's going on, but I will not waste much time without progress.

Excited to see the math in action :)

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by boopcamt** [comment]
:bulb: 

Ah I think I understand... this repo has multiple user workflows. And the maintainer is using his own stuff, thereby breaking Biggie's commandment # 4 https://www.youtube.com/watch?v=w6Z8JGzggIc&t=74s

Seriously though, any [java person](https://en.wikipedia.org/wiki/Java_Man) would know what to do with this repo because it's just a big java module, right? I should be able to plop eclipse right into things.

I feel like a toddler. No more housekeeping/bikeshedding, that dog won't hunt. I was barking up the wrong tree, best to let sleeping dogs lie.
